version: '3.9'

services:
    web:
        build: .
        depends_on:
            - db
        env_file: .env
        volumes:
            - .:/code
        ports:
            - 4000:8000
    db:
        image: postgres:14
        env_file:
            - .env
        volumes:
            - .data/postgres_data:/var/lib/postgresql/data/
