version: '3.9'

services:
    web:
        build: .
        depends_on:
            - db
        links:
            - db
        env_file: ./.env
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 4000:8000
    db:
        image: postgres:14
        env_file:
            - ./.env
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
