# Generated by Django 4.0.4 on 2022-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='page.page'),
        ),
    ]
