# Generated by Django 4.0.5 on 2022-06-22 12:28

from django.conf import settings
from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("page", "0003_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="follow_requests",
            field=models.ManyToManyField(
                blank=True, related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follows", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.URLField(
                blank=True, null=True, validators=[page.models.validate_url]
            ),
        ),
    ]
