# Generated by Django 4.0.5 on 2022-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_alter_page_follow_requests_alter_page_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="pages", to="page.tag"
            ),
        ),
    ]
