# Generated by Django 4.0.5 on 2022-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_alter_page_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="page.page"
            ),
        ),
    ]
