# Generated by Django 4.0.5 on 2022-06-22 12:24

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_s3_path",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[page.models.validate_url],
            ),
        ),
    ]
